### ISSUE TITLE
`updateGraph: semver-mode`  not working for cross-channel upgrade

### ISSUE THREAD

**Issue by abhishekdwivedi3060** [k8s-operatorhub/community-operators#3069]
Refer Aerospike Kubernetes Operator 3.0.0 PR: https://github.com/k8s-operatorhub/community-operators/pull/3065

In 3.0.0 version of Aerospike Kubernetes Operator, we changed the channel from `alpha` to `stable` and as per `semver` mode in the `ci.yaml`, the latest 3.0.0 version (stable channel) should replace the old 2.5.0 (alpha channel) version.   But after the latest operatorhub catalog was published, there is no replaces section for `aerospike-kubernetes-operator.v2.5.0` under `aerospike-kubernetes-operator.v3.0.0` version and as a result there is no upgrade path available.

```
k exec -it operatorhubio-catalog-559jh -n olm -- sh                                          
/ $ cd /configs/aerospike-kubernetes-operator/
/configs/aerospike-kubernetes-operator $
```

Below is the output of `catalog.yaml` of Aerospike Kubernetes Operator from inside the operatorhub catalog pod.

```
---
defaultChannel: stable
icon:
  base64data: PHN2ZyB3aWR0aD0iMjUwMCIgaGVpZ2h0PSIyNTAwIiB2aWV3Qm94PSIwIDAgMjU2IDI1NiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJ4TWlkWU1pZCI+PHBhdGggZD0iTTAgMGgyNTZ2MjU2SDBWMHoiIG
ZpbGw9IiNCMDI1MkEiLz48cGF0aCBkPSJNMTU2LjI5MyA5NS42MDVsLTczLjE2OSAzMi41OTQgNzMuMTcgMzIuODFWOTUuNjA1em0tOTIuMDMyIDM5Ljk3OWwtMTcuMDQ5LTcuMyAxNy4wNDktNy44ODIgMTQ0LjUyNy02NS4zNzZ2MTcuNDAzbC0zNy45MzIgMTYuODI0djc4LjExN2
wzNy45MzIgMTd2MTYuNjA0TDY0LjI2IDEzNS41ODR6IiBmaWxsPSIjRkZGIi8+PC9zdmc+
  mediatype: image/svg+xml
name: aerospike-kubernetes-operator
schema: olm.package
---
entries:
- name: aerospike-kubernetes-operator.v2.0.0
- name: aerospike-kubernetes-operator.v2.1.0
  replaces: aerospike-kubernetes-operator.v2.0.0
- name: aerospike-kubernetes-operator.v2.2.0
  replaces: aerospike-kubernetes-operator.v2.1.0
- name: aerospike-kubernetes-operator.v2.2.1
  replaces: aerospike-kubernetes-operator.v2.2.0
- name: aerospike-kubernetes-operator.v2.3.0
  replaces: aerospike-kubernetes-operator.v2.2.1
- name: aerospike-kubernetes-operator.v2.4.0
  replaces: aerospike-kubernetes-operator.v2.3.0
- name: aerospike-kubernetes-operator.v2.5.0
  replaces: aerospike-kubernetes-operator.v2.4.0
name: alpha
package: aerospike-kubernetes-operator
schema: olm.channel
---
entries:
- name: aerospike-kubernetes-operator.v3.0.0
name: stable
package: aerospike-kubernetes-operator
schema: olm.channel
---
```  

Steps done to upgrade: 
1. Edit the existing subscription of `aerospike-kubernetes-operator.v2.5.0` and change the channel from `alpha` to `stable`.

Expected outcome:
1. New installPlan for `aerospike-kubernetes-operator.v3.0.0` should be created and operator should be upgraded to `3.0.0` as per `installPlanApproval` policy.

Is `updateGraph: semver-mode`  not supported for cross-channel upgrades? 
Are there any extra steps required for cross-channel upgrade with server-mode?
