### ISSUE TITLE
Keycloak operator v22.0.4 deploy Keycloak nightly by default

### ISSUE THREAD

**Issue by dorianm** [k8s-operatorhub/community-operators#3323]
Hey,

Keycloak Operator 22.0.4 has been released yesterday (#3318) but the operator is configured to deploy nightly version by default instead of 22.0.4 : 

See https://github.com/k8s-operatorhub/community-operators/blob/main/operators/keycloak-operator/22.0.4/manifests/keycloak-operator.clusterserviceversion.yaml#L91 :

```yaml
                  - env:
                       - name: OPERATOR_KEYCLOAK_IMAGE
                         value: quay.io/keycloak/keycloak:nightly
```

Our Keycloak cluster has been upgraded to nightly today. I think other users will encounter the same problem.

/cc @vmuzikar
