### ISSUE TITLE
[operators/prometheus] cant monitor outside his namespace

### ISSUE THREAD

**Issue by zfrhv** [k8s-operatorhub/community-operators#942]
As I already described [here](https://github.com/prometheus-operator/prometheus-operator/issues/4601) prometheus cant monitor outside of his namespace.

could you please change in the csv of the operator args from this:
```yaml
        - -namespaces=$(NAMESPACES)
```
to this:
```yaml
        - --prometheus-instance-namespaces=$(NAMESPACES)
        - --alertmanager-instance-namespaces=$(NAMESPACES)
        - --thanos-ruler-instance-namespaces=$(NAMESPACES)
```

and also the promehteus easily exeeding his resources, so could you please also edit the resources from this:
```yaml
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
```
to this:
```yaml
resources:
  limits:
    cpu: 300m
    memory: 3Gi
  requests:
    cpu: 100m
    memory: 100Mi
```

in [here](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/prometheus/0.47.0/prometheusoperator.0.47.0.clusterserviceversion.yaml#L327) and [here](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/prometheus/0.47.0/prometheusoperator.0.47.0.clusterserviceversion.yaml#L339-L345)
